name: flutter_motion_ui
description: "A beautiful collection of 80+ animated Flutter components with smooth motions and modern design trends. Includes buttons, cards, animations, navigation, and more for building stunning Flutter applications."
version: 1.0.3
homepage: https://github.com/lyhorngcnb/flutter_motion_ui
repository: https://github.com/lyhorngcnb/flutter_motion_ui
issue_tracker: https://github.com/lyhorngcnb/flutter_motion_ui/issues

environment:
  sdk: ">=3.0.0 <4.0.0"  # ✅ Proper SDK constraint
  flutter: ">=3.0.0"  # ✅ Updated Flutter constraint

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4  # ✅ Added for animations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: